AllCops:
  TargetRubyVersion: 4.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
    - "benchmark/regex-redux.rb"
