# frozen_string_literal: true

module CoreMvpCorpus
  CASES = [
    { id: 'literal-match', feature: :literal, pattern: 'cat', options: 0, input: 'cat', expected: :match,
      supported: true },
    { id: 'literal-no-match', feature: :literal, pattern: 'cat', options: 0, input: 'dog', expected: :no_match,
      supported: true },
    { id: 'unicode-literal', feature: :utf8, pattern: '日本', options: 0, input: '日本語', expected: :match,
      supported: true },
    { id: 'ascii8bit-literal', feature: :ascii8bit, pattern: "\xFF".b, options: 0, input: "\xFF".b, expected: :match,
      supported: true },
    { id: 'concatenation', feature: :concatenation, pattern: 'ab', options: 0, input: 'xxabyy', expected: :match,
      supported: true },
    { id: 'alternation-left', feature: :alternation, pattern: 'cat|dog', options: 0, input: 'dog', expected: :match,
      supported: true },
    { id: 'capture', feature: :capture, pattern: '(ab)(cd)', options: 0, input: 'abcd', expected: :match,
      supported: true },
    { id: 'greedy-star', feature: :quantifier, pattern: 'a*', options: 0, input: 'aa', expected: :match,
      supported: true },
    { id: 'greedy-plus', feature: :quantifier, pattern: 'a+', options: 0, input: 'aaa', expected: :match,
      supported: true },
    { id: 'optional', feature: :quantifier, pattern: 'ab?c', options: 0, input: 'ac', expected: :match,
      supported: true },
    { id: 'bounded-quantifier', feature: :quantifier, pattern: 'a{2,4}', options: 0, input: 'aaa', expected: :match,
      supported: true },
    { id: 'character-class', feature: :character_class, pattern: '[abc]', options: 0, input: 'b', expected: :match,
      supported: true },
    { id: 'negated-character-class', feature: :character_class, pattern: '[^a]', options: 0, input: 'b',
      expected: :match, supported: true },
    { id: 'character-range', feature: :character_class, pattern: '[a-z]', options: 0, input: 'm', expected: :match,
      supported: true },
    { id: 'digit-escape', feature: :escape, pattern: '\\d+', options: 0, input: '123', expected: :match,
      supported: true },
    { id: 'space-escape', feature: :escape, pattern: '\\s', options: 0, input: ' ', expected: :match, supported: true },
    { id: 'word-escape', feature: :escape, pattern: '\\w+', options: 0, input: 'word_1', expected: :match,
      supported: true },
    { id: 'escaped-metacharacter', feature: :escape, pattern: '\\.', options: 0, input: '.', expected: :match,
      supported: true },
    { id: 'start-anchor', feature: :anchor, pattern: '^cat', options: 0, input: 'cat nap', expected: :match,
      supported: true },
    { id: 'end-anchor', feature: :anchor, pattern: 'cat$', options: 0, input: 'copycat', expected: :match,
      supported: true },
    { id: 'case-insensitive', feature: :option, pattern: 'cat', options: :ignorecase, input: 'CAT', expected: :match,
      supported: true },
    { id: 'multiline', feature: :option, pattern: '^cat$', options: :multiline, input: "dog\ncat\nfox",
      expected: :match, supported: true },
    { id: 'lookahead-deferred', feature: :lookaround, pattern: 'a(?=b)', options: 0, input: 'ab',
      expected: :unsupported, supported: false },
    { id: 'backreference-deferred', feature: :backreference, pattern: '(a)\\1', options: 0, input: 'aa',
      expected: :unsupported, supported: false },
    { id: 'named-capture-deferred', feature: :named_capture, pattern: '(?<word>cat)', options: 0, input: 'cat',
      expected: :unsupported, supported: false },
    { id: 'unicode-property-deferred', feature: :unicode_property, pattern: '\\p{Hiragana}', options: 0, input: 'あ',
      expected: :unsupported, supported: false }
  ].freeze
end
