Init_onibi(void)
{
    id_initialize = rb_intern("initialize");
    id_new = rb_intern("new");
    id_match = rb_intern("match");
    id_aref = rb_intern("[]");
    id_instance_method = rb_intern("instance_method");
    id_bind = rb_intern("bind");
    id_call = rb_intern("call");
    id_bytebegin = rb_intern("bytebegin");
    id_byteend = rb_intern("byteend");
    id_length = rb_intern("length");
    id_source = rb_intern("source");
    id_options = rb_intern("options");
    id_inspect = rb_intern("inspect");
    id_to_s = rb_intern("to_s");
    id_encoding = rb_intern("encoding");
    id_index = rb_intern("index");
    id_a_assert_begin_buffer = rb_intern("ASSERT_BEGIN_BUFFER");
    id_a_assert_search_origin = rb_intern("ASSERT_SEARCH_ORIGIN");
    id_a_assert_end_buffer = rb_intern("ASSERT_END_BUFFER");
    id_a_assert_begin_line = rb_intern("ASSERT_BEGIN_LINE");
    id_a_assert_end_line = rb_intern("ASSERT_END_LINE");
    id_a_assert_word_boundary = rb_intern("ASSERT_WORD_BOUNDARY");
    id_a_assert_nonword_boundary = rb_intern("ASSERT_NONWORD_BOUNDARY");
    id_a_assert_semi_end_buffer = rb_intern("ASSERT_SEMI_END_BUFFER");
    id_a_assert_lookahead = rb_intern("ASSERT_LOOKAHEAD");
    id_a_assert_lookbehind = rb_intern("ASSERT_LOOKBEHIND");
    id_pred_byte = rb_intern("byte");
    id_pred_bitmap = rb_intern("bitmap");
    id_pred_any = rb_intern("any");
    id_opt_ignorecase = rb_intern("ignorecase");
    id_opt_multiline = rb_intern("multiline");
    id_opt_extended = rb_intern("extended");
    id_opt_fixedencoding = rb_intern("fixedencoding");
    id_opt_noencoding = rb_intern("noencoding");
    id_prop_ascii = rb_intern("ASCII");
    id_prop_ascii_hex = rb_intern("ASCII_Hex_Digit");
    id_key_op = rb_intern("op");
    id_key_multiline = rb_intern("multiline");
    id_key_ignorecase = rb_intern("ignorecase");
    id_key_kind = rb_intern("kind");
    id_key_kind_code = rb_intern("kind_code");
    id_key_opcode = rb_intern("opcode");
    id_key_assert_kind = rb_intern("assert_kind");
    id_key_predicate_code = rb_intern("predicate_code");
    id_key_byte = rb_intern("byte");
    id_key_capture = rb_intern("capture");
    id_key_start = rb_intern("start");
    id_key_end = rb_intern("end");
    id_key_captures = rb_intern("captures");
    id_key_subprogram = rb_intern("subprogram");
    id_key_entry = rb_intern("entry");
    id_key_slot = rb_intern("slot");
    id_key_set = rb_intern("set");
    id_key_value = rb_intern("value");
    id_key_type_code = rb_intern("type_code");
    id_key_name = rb_intern("name");
    id_key_name_id = rb_intern("name_id");
    id_key_ctype = rb_intern("ctype");
    id_key_ranges = rb_intern("ranges");
    id_key_children = rb_intern("children");
    id_key_operands = rb_intern("operands");
    id_key_body = rb_intern("body");
    id_key_options = rb_intern("options");
    id_key_negative_options = rb_intern("negative_options");
    id_key_capturing = rb_intern("capturing");
    id_key_condition = rb_intern("condition");
    id_key_branches = rb_intern("branches");
    id_key_yes = rb_intern("yes");
    id_key_no = rb_intern("no");
    id_key_atom = rb_intern("atom");
    id_key_min = rb_intern("min");
    id_key_max = rb_intern("max");
    id_key_width = rb_intern("width");
    id_key_greedy = rb_intern("greedy");
    id_key_possessive = rb_intern("possessive");
    id_key_negated = rb_intern("negated");
    id_key_bitmap = rb_intern("bitmap");
    id_key_preserve_if_set = rb_intern("preserve_if_set");
    id_key_limit = rb_intern("limit");
    id_key_positive = rb_intern("positive");
    id_key_inline_ignorecase = rb_intern("inline_ignorecase");
    id_key_predicates = rb_intern("predicates");
    id_key_bytes = rb_intern("bytes");
    id_key_blob = rb_intern("blob");
    id_key_header = rb_intern("header");
    id_key_edges = rb_intern("edges");
    id_key_from = rb_intern("from");
    id_key_accept = rb_intern("accept");
    id_key_action_offset = rb_intern("action_offset");
    id_key_flags = rb_intern("flags");
    id_key_id = rb_intern("id");
    id_key_capture_count = rb_intern("capture_count");
    id_key_counter_count = rb_intern("counter_count");
    id_key_state_count = rb_intern("state_count");
    id_key_features = rb_intern("features");
    id_key_edge_count = rb_intern("edge_count");
    id_key_action_count = rb_intern("action_count");
    id_key_class_count = rb_intern("class_count");
    id_key_subprogram_count = rb_intern("subprogram_count");
    id_key_start_edge_base = rb_intern("start_edge_base");
    id_key_start_edge_count = rb_intern("start_edge_count");
    id_key_blob_size = rb_intern("blob_size");
    id_key_literal_count = rb_intern("literal_count");
    id_key_version = rb_intern("version");
    id_key_semantic_capture_count = rb_intern("semantic_capture_count");
    id_key_states_offset = rb_intern("states_offset");
    id_key_edges_offset = rb_intern("edges_offset");
    id_key_actions_offset = rb_intern("actions_offset");
    id_key_classes_offset = rb_intern("classes_offset");
    id_key_literals_offset = rb_intern("literals_offset");
    id_key_descriptors_offset = rb_intern("descriptors_offset");
    id_key_subprograms_offset = rb_intern("subprograms_offset");
    id_key_negative_name = rb_intern("negative_name");
    id_key_negative = rb_intern("negative");
    id_anchor = rb_intern("anchor");
    id_anchor_start = rb_intern("anchor_start");
    id_anchor_end = rb_intern("anchor_end");
    id_insert = rb_intern("insert");
    id_timeout = rb_intern("timeout");
    id_encode = rb_intern("encode");
    id_message = rb_intern("message");
    id_names = rb_intern("names");
    id_named_captures = rb_intern("named_captures");
    id_escape = rb_intern("escape");
    id_union = rb_intern("union");
    id_to_regexp = rb_intern("to_regexp");
    id_kind_literal = rb_intern("literal");
    id_recursive_marker = rb_intern("__onibi_recursive_call__");
    mOnibi = rb_define_module("Onibi");
    eRegexpError =
	rb_define_class_under(mOnibi, "RegexpError", rb_eRegexpError);
    /* Lexer, parser, compiler, RSeq, and VM are implementation objects.
     * Keep their methods available to the C pipeline, but do not publish
     * Ruby constants for them.  Only Onibi::Regexp is public. */
    cRegexp = rb_define_class_under(mOnibi, "Regexp", rb_cObject);
    eTimeoutError =
	rb_define_class_under(cRegexp, "TimeoutError", eRegexpError);
    rb_define_singleton_method(cRegexp, "timeout=", onibi_timeout_set, 1);
    rb_define_singleton_method(cRegexp, "timeout", onibi_timeout_default, 0);
    rb_define_singleton_method(cRegexp, "escape", onibi_regexp_escape, 1);
    rb_define_singleton_method(cRegexp, "quote", onibi_regexp_escape, 1);
    rb_define_singleton_method(cRegexp, "union", onibi_regexp_union, -1);
    rb_define_singleton_method(cRegexp, "try_convert", onibi_regexp_try_convert,
			       1);
    rb_define_singleton_method(cRegexp, "linear_time?",
			       onibi_regexp_linear_time_p, 1);
    rb_define_singleton_method(cRegexp, "last_match", onibi_last_match, -1);
    rb_define_alloc_func(cRegexp, onibi_alloc);
    rb_define_method(cRegexp, "initialize", onibi_initialize, -1);
    rb_define_method(cRegexp, "match", onibi_match, -1);
    rb_define_method(cRegexp, "===", onibi_case_equal, 1);
    rb_define_method(cRegexp, "~", onibi_tilde, 0);
    rb_define_method(cRegexp, "match?", onibi_match_p, -1);
    rb_define_method(cRegexp, "source", onibi_source, 0);
    rb_define_method(cRegexp, "names", onibi_names, 0);
    rb_define_method(cRegexp, "named_captures", onibi_named_captures, 0);
    rb_define_method(cRegexp, "casefold?", onibi_casefold_p, 0);
    rb_define_method(cRegexp, "==", onibi_equal, 1);
    rb_define_method(cRegexp, "eql?", onibi_equal, 1);
    rb_define_method(cRegexp, "hash", onibi_hash, 0);
    rb_define_method(cRegexp, "options", onibi_options, 0);
    rb_define_method(cRegexp, "fixed_encoding?", onibi_fixed_encoding_p, 0);
    rb_define_method(cRegexp, "no_encoding?", onibi_no_encoding_p, 0);
    rb_define_method(cRegexp, "inspect", onibi_inspect, 0);
    rb_define_method(cRegexp, "to_s", onibi_to_s, 0);
    rb_define_method(cRegexp, "encoding", onibi_encoding, 0);
    rb_define_method(cRegexp, "timeout", onibi_timeout, 0);
    rb_define_method(cRegexp, "scan", onibi_scan, 1);
    rb_define_method(cRegexp, "gsub", onibi_gsub, -1);
    rb_define_private_method(cRegexp, "__onibi_diagnostics__",
			     onibi_diagnostics_for, 1);
    rb_define_const(cRegexp, "IGNORECASE", INT2NUM(1));
    rb_define_const(cRegexp, "EXTENDED", INT2NUM(2));
    rb_define_const(cRegexp, "MULTILINE", INT2NUM(4));
    rb_define_const(cRegexp, "FIXEDENCODING", INT2NUM(16));
    rb_define_const(cRegexp, "NOENCODING", INT2NUM(32));
}
