module Onibi
  VERSION: String

  class Error < StandardError
  end

  class RegexpError < Error
  end

  class Regexp
    class TimeoutError < RegexpError
    end

    IGNORECASE: Integer
    EXTENDED: Integer
    MULTILINE: Integer
    FIXEDENCODING: Integer
    NOENCODING: Integer

    def self.compile: (String pattern, ?Array[String]? options, ?timeout: Numeric?) -> Regexp
                      | (String pattern, ?Integer options, ?timeout: Numeric?) -> Regexp
                      | (String pattern, ?(String | Symbol | bool) options, ?timeout: Numeric?) -> Regexp
                      | (::Regexp pattern, ?timeout: Numeric?) -> Regexp
                      | (Regexp pattern, ?timeout: Numeric?) -> Regexp
    def self.escape: (untyped string) -> String
    def self.quote: (untyped string) -> String
    def self.try_convert: (untyped value) -> Regexp?
    def self.union: (Array[String] patterns) -> Regexp
                   | (Array[::Regexp | String] patterns) -> Regexp
                   | (*String patterns) -> Regexp
                   | (*(::Regexp | String) patterns) -> Regexp
    def self.linear_time?: (String | ::Regexp | Regexp pattern) -> bool
    def self.dfa_memory_budget: () -> Integer
    def self.dfa_memory_budget=: (Integer value) -> Integer
    def self.timeout: () -> Float?
    def self.timeout=: (Numeric? value) -> Float?

    def initialize: (String pattern, ?Array[String]? options, ?timeout: Numeric?) -> void
                  | (String pattern, ?Integer options, ?timeout: Numeric?) -> void
                  | (String pattern, ?(String | Symbol | bool) options, ?timeout: Numeric?) -> void
                  | (::Regexp pattern, ?timeout: Numeric?) -> void
                  | (Regexp pattern, ?timeout: Numeric?) -> void
    def match?: (String input, ?Numeric position) -> bool
    def match: (String input, ?Numeric position) -> MatchData?
    def timeout: () -> Float?
    def =~: (String input) -> Integer?
    def ===: (String input) -> bool
    def ~: () -> Integer?
    def encoding: () -> Encoding
    def fixed_encoding?: () -> bool
    def options: () -> Integer
    def source: () -> String
    def casefold?: () -> bool
    def names: () -> Array[String]
    def named_captures: () -> Hash[String, Array[Integer]]
    def ==: (untyped other) -> bool
    def eql?: (untyped other) -> bool
    def hash: () -> Integer
    def to_s: () -> String
    def inspect: () -> String
  end

  class MatchData
    def []: (Integer index) -> String?
          | (Range[Integer] index) -> Array[String?]
          | (String | Symbol index) -> String?
    def match: (Integer | String | Symbol index) -> String?
    def captures: () -> Array[String?]
    def offset: (Integer | String | Symbol index) -> [Integer, Integer]?
    def begin: (Integer | String | Symbol index) -> Integer?
    def end: (Integer | String | Symbol index) -> Integer?
    def to_a: () -> Array[String?]
    def length: () -> Integer
    def size: () -> Integer
    def values_at: (*untyped indices) -> Array[String?]
    def string: () -> String?
    def regexp: () -> Regexp?
    def pre_match: () -> String?
    def post_match: () -> String?
    def bytebegin: (Integer | String | Symbol index) -> Integer?
    def byteend: (Integer | String | Symbol index) -> Integer?
    def byteoffset: (Integer | String | Symbol index) -> [Integer, Integer]?
    def match_length: (Integer | String | Symbol index) -> Integer?
    def named_captures: () -> Hash[String, String?]
    def names: () -> Array[String]
    def deconstruct: () -> Array[String?]
    def deconstruct_keys: (Array[Symbol] keys) -> Hash[Symbol, String?]
      | (nil keys) -> Hash[Symbol, String?]
    def to_s: () -> String?
    def inspect: () -> String
    def ==: (untyped other) -> bool
    def eql?: (untyped other) -> bool
    def hash: () -> Integer
  end
end
