module Onibi
  VERSION: String

  class Error < StandardError
  end

  class RegexpError < Error
  end

  class Regexp
    IGNORECASE: Integer
    MULTILINE: Integer
    FIXEDENCODING: Integer
    NOENCODING: Integer

    def self.compile: (String pattern) -> Regexp
                      | (String pattern, Array[String]? options) -> Regexp
                      | (String pattern, Integer options) -> Regexp
                      | (Regexp pattern) -> Regexp
    def self.escape: (untyped string) -> String
    def self.union: (*String patterns) -> Regexp
    def self.dfa_memory_budget: () -> Integer
    def self.dfa_memory_budget=: (Integer value) -> Integer

    def initialize: (String pattern) -> void
                  | (String pattern, Array[String]? options) -> void
                  | (String pattern, Integer options) -> void
                  | (Regexp pattern) -> void
    def match?: (String input) -> bool
    def match: (String input) -> MatchData?
    def =~: (String input) -> Integer?
    def ===: (String input) -> bool
    def ~: () -> Integer?
    def encoding: () -> Encoding
    def fixed_encoding?: () -> bool
    def options: () -> (Array[String] | Integer)
    def source: () -> String
    def casefold?: () -> bool
    def ==: (untyped other) -> bool
    def eql?: (untyped other) -> bool
    def hash: () -> Integer
  end

  class MatchData
    def []: (Integer index) -> String?
          | (Range[Integer] index) -> Array[String?]
    def captures: () -> Array[String?]
    def offset: (Integer index) -> [Integer, Integer]?
    def begin: (Integer index) -> Integer?
    def end: (Integer index) -> Integer?
    def to_a: () -> Array[String?]
    def length: () -> Integer
    def size: () -> Integer
    def values_at: (*untyped indices) -> Array[String?]
    def string: () -> String?
    def regexp: () -> Regexp?
    def pre_match: () -> String?
    def post_match: () -> String?
    def named_captures: () -> Hash[String, String?]
    def names: () -> Array[String]
  end
end
