#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate the encoding capability table used by Onibi::EncodingSupport.
#
# Ruby exposes encoding capabilities through Encoding objects.  The matcher
# needs a stable policy table, so resolve that information once when the gem
# source is generated.  Runtime code performs a name lookup only.

PROJECT_ROOT = File.expand_path("..", __dir__)
DEFAULT_OUTPUT = File.join(PROJECT_ROOT, "lib/onibi/encoding/generated_profiles.rb")

UNICODE_ENCODINGS = %w[UTF-8 UTF-16BE UTF-16LE UTF-32BE UTF-32LE].freeze
LEGACY_MULTIBYTE_ENCODINGS = %w[EUC-JP Windows-31J].freeze
PROPERTY_ENCODING_OVERRIDES = {
  "ASCII-8BIT" => :ascii,
  "EUC-JP" => :legacy_multibyte,
  "ISO-8859-1" => :ascii,
  "US-ASCII" => :ascii,
  "Windows-31J" => :legacy_multibyte
}.freeze
BINARY_ESCAPE_MULTIBYTE_ENCODINGS = %w[EUC-JP UTF-8 Windows-31J].freeze

def family_for(encoding)
  return :binary if encoding.name == "ASCII-8BIT"
  return :ascii if encoding.name == "US-ASCII"
  return :unicode if UNICODE_ENCODINGS.include?(encoding.name)
  return :legacy_multibyte if LEGACY_MULTIBYTE_ENCODINGS.include?(encoding.name)

  encoding.ascii_compatible? ? :ascii_compatible : :non_ascii_compatible
end

def property_mode_for(encoding)
  PROPERTY_ENCODING_OVERRIDES.fetch(encoding.name) do
    UNICODE_ENCODINGS.include?(encoding.name) ? :unicode : :ascii
  end
end

def row_for(encoding)
  {
    name: encoding.name,
    family: family_for(encoding),
    ascii_compatible: encoding.ascii_compatible?,
    dummy: encoding.dummy?,
    property_mode: property_mode_for(encoding),
    binary_escape_multibyte: BINARY_ESCAPE_MULTIBYTE_ENCODINGS.include?(encoding.name)
  }
end

def ruby_literal(value)
  value.inspect
end

def render(rows)
  body = rows.each_with_index.map do |row, index|
    comma = index == rows.length - 1 ? "" : ","
    "      #{ruby_literal(row[:name])} => [#{row[:family].inspect}, #{row[:ascii_compatible]}, " \
      "#{row[:dummy]}, #{row[:property_mode].inspect}, #{row[:binary_escape_multibyte]}]#{comma}"
  end.join("\n")

  <<~RUBY
    # frozen_string_literal: true

    # This file is generated by script/generate_encoding_profiles.rb.
    # Do not edit this file by hand.  The table is static at runtime so encoding
    # policy does not depend on the host's mutable Encoding registry.

    module Onibi
      module EncodingSupport
        PROFILE_ROWS = {
    #{body}
        }.freeze

        PROFILE_BY_NAME.replace(
          PROFILE_ROWS.to_h do |name, values|
            family, ascii_compatible, dummy, property_mode, binary_escape_multibyte = values
            [name, Profile.new(name: name, family: family, ascii_compatible: ascii_compatible,
                               dummy: dummy, property_mode: property_mode,
                               binary_escape_multibyte: binary_escape_multibyte).freeze]
          end
        )
        PROFILE_BY_NAME.freeze
      end
    end
  RUBY
end

output = ARGV.reject { |argument| argument == "--check" }.first || DEFAULT_OUTPUT
expected = render(Encoding.list.sort_by(&:name).map { |encoding| row_for(encoding) })

if ARGV.include?("--check")
  abort "#{output} is not up to date" unless File.file?(output) && File.read(output) == expected
else
  File.write(output, expected)
end
